name: Backend CI

on:
  push:
    branches:
      - develop  
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main  
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven verify (with google-java-format check)
      run: mvn verify --file backend/pom.xml
      env:
        MAVEN_OPTS: "--add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED"
        
    - name: Build with Maven
      run: mvn -B clean install --file backend/pom.xml
      
    - name: Run Tests
      run: mvn -B test --file backend/pom.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: backend/target/site/jacoco/
        retention-days: 14
